#!/bin/sh

# cleanup
rm -rf obj_dir

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace depth_calculator_LUT.sv --exe depth_calculator_LUT_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdepth_calculator_LUT.mk Vdepth_calculator_LUT

# run executable simulation 
obj_dir/Vdepth_calculator_LUT