#!/bin/sh

# cleanup
rm -rf obj_dir

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe no_vcd_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation 
obj_dir/Vtop