#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f AXIS_tb.vcd

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace pixel_generator.v --exe AXIS.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpixel_generator.mk Vpixel_generator

# run executable simulation 
obj_dir/Vpixel_generator