#!/bin/sh

# cleanup
rm -rf obj_dir

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top_connection.sv --exe top_connection_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_connection.mk Vtop_connection

# run executable simulation 
obj_dir/Vtop_connection